In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
PROJECT_PATH = '/home/swei20/PIML_v1/'
import sys
sys.path.insert(0, PROJECT_PATH)

In [3]:
import os
import numpy as np

In [7]:
from PIML.gateway.loaderIF.baseloaderIF import SpecGridLoaderIF


In [10]:
GRID_PATH="/datascope/subaru/user/swei20/data/pfsspec/import/stellar/grid"
FILE_PATH=os.path.join(GRID_PATH, "bosz_5000_RHB.h5")

In [ ]:
PARAMS = {
    "data": {
        "DATA_PATH": FILE_PATH
        "arm"      : "W"
    }
    
    "op: : {
        "Arm" : 
    }
        
}

In [13]:
SGL = SpecGridLoaderIF()
SGL.set_data_path(FILE_PATH)
SpecGrid = SGL.load()

In [4]:
from PIML.surface.database.baseloader import H5pyLoader

In [5]:
loader = H5pyLoader()

In [7]:
arg = "wave"
wave = loader.load_arg(FILE_PATH, arg)
wave

array([ 3000.2639,  3000.564 ,  3000.8643, ..., 13996.3662, 13997.7656,
       13999.166 ])

In [12]:

class SplitOperation():
    """ class for splitting data. """
    def __init__(self, split_idxs) -> None:
        self.startIdx = split_idxs[0]
        self.endIdx = split_idxs[1]

    def perform(self, data):
        return data[..., self.startIdx:self.endIdx]



In [ ]:
SpecGrid

In [44]:
class ArmSplitOperation(SplitOperation):
    """ class for splitting data. """
    def __init__(self, arm: str, wave: np.ndarray) -> None:
        self.arm = arm
        self.wRng = [7100, 8500]
        # wRng = PARAMS["wave_rng"]
        self.split_idxs = np.digitize(self.wRng, wave)
        super().__init__(self.split_idxs)

    

In [45]:
a = ArmSplitOperation("W", SpecGrid.wave)

In [46]:
wave = SpecGrid.wave

In [47]:
a.perform(wave)

array([7100.0293, 7100.7393, 7101.4492, ..., 8497.7256, 8498.5752,
       8499.4258])

In [48]:
wave

array([ 3000.2639,  3000.564 ,  3000.8643, ..., 13996.3662, 13997.7656,
       13999.166 ])

In [43]:
a.split_idxs

array([0, 0, 0, ..., 2, 2, 2])