In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
PROJECT_PATH = '/home/swei20/PIML_v1/'
import sys
sys.path.insert(0, PROJECT_PATH)

In [4]:
import os
import numpy as np
import matplotlib.pyplot as plt


In [4]:
from PIML.gateway.loaderIF.nnpreploaderIF import StellarNNPrepLoaderIF

ModuleNotFoundError: No module named 'PIML.gateway.loaderIF.nnpreploaderIF'

In [ ]:
loader = StellarNNPrepLoaderIF()

In [ ]:
DATA_DIR = "/home/swei20/PIML_v1/test/testdata/testnnprepdata"

In [7]:
loader.set_path(DATA_DIR)

In [8]:
NNP = loader.load()

In [44]:
PARAMS = {
    "object": {"path":"/home/swei20/PIML_v1/test/testdata/testprepnndata", "arm": "RedM", "res": 1000},
    "data": {"rng" : np.array([4., 5., 3., 5., 3.])},
    "op": {"step": 10, "ntrain": 5, "ntest": 5, "seed":922},
    "model": {},
    "out": {"path": "/datascope/subaru/user/swei20/data/pfsspec/prepnn/"},
}

In [5]:
from PIML.gateway.processIF.nnprocessIF.prepnnprocessIF import StellarPrepNNProcessIF

In [6]:
PP = StellarPrepNNProcessIF()

In [7]:
PP.interact(PARAMS)

NameError: name 'PARAMS' is not defined

In [48]:
PP.finish()

AttributeError: 'PrepNN' object has no attribute 'train_name'

In [30]:
PP.OP_OUT

{'path': '/datascope/subaru/user/swei20/data/pfsspec/prepnn/'}

In [43]:
PP.Object.__dict__

{'interpolator': <scipy.interpolate._rbfinterp.RBFInterpolator at 0x7fcf72882280>,
 'sky': array([0.15077469, 0.1495934 , 0.14423648, 0.14433482, 0.14747137,
        0.14836056, 0.14531086, 0.14922931, 0.14873182, 0.14719386,
        0.14742225, 0.14853853, 0.14872931, 0.14798906, 0.14843427,
        0.14942387, 0.15094892, 0.15054792, 0.15677576, 0.19068839,
        0.17415853, 0.15311395, 0.15320229, 0.16651898, 0.17029691,
        0.15508382, 0.18025812, 0.1883331 , 0.16233235, 0.16886398,
        0.16669567, 0.15809255, 0.31407816, 0.52847163, 0.16061403,
        0.16233161, 0.16050382, 0.16841212, 0.16914596, 0.16412062,
        0.1623135 , 0.16355638, 0.17055147, 0.17649125, 0.16981551,
        0.16835615, 0.16894306, 0.16776282, 0.1689735 , 0.17108565,
        0.21743374, 0.21017425, 0.18578376, 0.17103679, 0.17821553,
        0.18634029, 0.19609469, 0.25088166, 0.22023136, 0.19109764,
        0.18437969, 0.18709035, 0.17928734, 0.24631951, 0.32752443,
        0.17920501, 0.1754

In [15]:
NNP = PP.Object

In [41]:
NNP.test_data

array([[14.29471548, 14.28819808, 14.28951243, ..., 13.93229754,
        13.94421155, 13.93452839],
       [14.58827979, 14.57858828, 14.57833561, ..., 14.18041872,
        14.19064549, 14.17801676],
       [14.80746089, 14.80181226, 14.7985106 , ..., 14.37420822,
        14.37924059, 14.36702607],
       ...,
       [14.78596441, 14.77069913, 14.77003987, ..., 14.3483457 ,
        14.35615064, 14.34016488],
       [14.94662332, 14.94297933, 14.94048079, ..., 14.49607531,
        14.49803132, 14.48542404],
       [14.33784199, 14.32170369, 14.32717317, ..., 13.95713021,
        13.97312491, 13.95968367]])

In [ ]:
from PIML.surfa

In [21]:
PP.finish("/home/swei20/PIML_v1/test/testdata/testnndata")

AttributeError: Can't pickle local object 'CoordxifyOperation.get_scalers.<locals>.<lambda>'

In [24]:
NNP.__dict__

{'interpolator': <scipy.interpolate._rbfinterp.RBFInterpolator at 0x7fb33651cc10>,
 'sky': array([0.15077469, 0.1495934 , 0.14423648, 0.14433482, 0.14747137,
        0.14836056, 0.14531086, 0.14922931, 0.14873182, 0.14719386,
        0.14742225, 0.14853853, 0.14872931, 0.14798906, 0.14843427,
        0.14942387, 0.15094892, 0.15054792, 0.15677576, 0.19068839,
        0.17415853, 0.15311395, 0.15320229, 0.16651898, 0.17029691,
        0.15508382, 0.18025812, 0.1883331 , 0.16233235, 0.16886398,
        0.16669567, 0.15809255, 0.31407816, 0.52847163, 0.16061403,
        0.16233161, 0.16050382, 0.16841212, 0.16914596, 0.16412062,
        0.1623135 , 0.16355638, 0.17055147, 0.17649125, 0.16981551,
        0.16835615, 0.16894306, 0.16776282, 0.1689735 , 0.17108565,
        0.21743374, 0.21017425, 0.18578376, 0.17103679, 0.17821553,
        0.18634029, 0.19609469, 0.25088166, 0.22023136, 0.19109764,
        0.18437969, 0.18709035, 0.17928734, 0.24631951, 0.32752443,
        0.17920501, 0.1754

In [20]:
PP.Object

# Testing

In [24]:
label = NNP.uniform_label_sampler(10)

In [25]:
data = NNP.generator(label)

In [26]:
label

array([[0.25868424, 0.96934641, 0.47115352, 0.92569345, 0.03883448],
       [0.58378153, 0.99175536, 0.61261031, 0.78233509, 0.69351177],
       [0.94400779, 0.14803447, 0.47572934, 0.00977451, 0.40640795],
       [0.36578621, 0.76332699, 0.51128634, 0.1799264 , 0.24498079],
       [0.60862879, 0.33633556, 0.48682995, 0.89279738, 0.58531972],
       [0.86367532, 0.69093168, 0.01866656, 0.32638412, 0.74510994],
       [0.67871864, 0.41119964, 0.67271401, 0.07525835, 0.49033854],
       [0.25852292, 0.99073078, 0.18548338, 0.37007307, 0.74814763],
       [0.79836086, 0.20472684, 0.06772367, 0.52988991, 0.53370376],
       [0.40653076, 0.58187066, 0.2242174 , 0.29812822, 0.53413694]])

In [27]:
data

array([[15.00444348, 14.9950023 , 14.9793557 , ..., 14.55326113,
        14.54621234, 14.5300963 ],
       [15.03448687, 15.02190534, 15.00576652, ..., 14.57367935,
        14.56677703, 14.54867415],
       [14.48046382, 14.45743942, 14.46292307, ..., 14.07881937,
        14.0927347 , 14.07763774],
       ...,
       [15.03183658, 15.0261476 , 15.01962717, ..., 14.59000232,
        14.58882531, 14.57243559],
       [14.52535314, 14.50413067, 14.50037549, ..., 14.12417621,
        14.13221501, 14.1172916 ],
       [14.76771675, 14.75972009, 14.75586212, ..., 14.34109144,
        14.34683634, 14.3336213 ]])

In [28]:
sigma = NNP.noiser(data)

In [29]:
sigma

array([[0.00017494, 0.00017577, 0.00017716, ..., 0.00021951, 0.00022029,
        0.00022209],
       [0.00017232, 0.00017341, 0.00017482, ..., 0.00021726, 0.00021802,
        0.00022002],
       [0.00022771, 0.00023037, 0.00022974, ..., 0.00027892, 0.00027696,
        0.00027909],
       ...,
       [0.00017255, 0.00017304, 0.00017361, ..., 0.00021549, 0.00021561,
        0.0002174 ],
       [0.00022262, 0.00022501, 0.00022544, ..., 0.00027259, 0.00027149,
        0.00027354],
       [0.00019705, 0.00019784, 0.00019822, ..., 0.0002443 , 0.00024359,
        0.00024522]])

In [30]:
sigma = NNP.Obs.get_log_sigma(data, log=1)

In [31]:
sigma

array([[0.00017494, 0.00017577, 0.00017716, ..., 0.00021951, 0.00022029,
        0.00022209],
       [0.00017232, 0.00017341, 0.00017482, ..., 0.00021726, 0.00021802,
        0.00022002],
       [0.00022771, 0.00023037, 0.00022974, ..., 0.00027892, 0.00027696,
        0.00027909],
       ...,
       [0.00017255, 0.00017304, 0.00017361, ..., 0.00021549, 0.00021561,
        0.0002174 ],
       [0.00022262, 0.00022501, 0.00022544, ..., 0.00027259, 0.00027149,
        0.00027354],
       [0.00019705, 0.00019784, 0.00019822, ..., 0.0002443 , 0.00024359,
        0.00024522]])