In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
PROJECT_PATH = '/home/swei20/PIML_v1/'
import sys
sys.path.insert(0, PROJECT_PATH)

In [3]:
import os
import numpy as np
import matplotlib.pyplot as plt


In [4]:
from PIML.gateway.loaderIF.nnpreploaderIF import StellarNNPrepLoaderIF

In [5]:
loader = StellarNNPrepLoaderIF()

In [6]:
DATA_DIR = "/home/swei20/PIML_v1/test/testdata/testnnprepdata"

In [7]:
loader.set_path(DATA_DIR)

In [8]:
NNP = loader.load()

In [9]:
PARAMS = {
    "data": {"rng" : np.array([4., 5., 3., 5., 3.])},
    "op": {"step": 10},
    "model": {},
}

In [30]:
from PIML.gateway.processIF.nnprepprocessIF.nnprepprocessIF import StellarNNPrepProcessIF

In [31]:
PP = StellarNNPrepProcessIF()

In [34]:
NNP.out = {"Obs": None, "uniform_label_sampler": None, "halton_label_sampler": None,"gen_data_from_label": None, "label_scaler": None, "label_rescaler": None}


In [35]:
PP.interact_on_NNPrep(PARAMS, NNP)

AttributeError: 'dict' object has no attribute 'label_scaler'

In [21]:
PP.finish("/home/swei20/PIML_v1/test/testdata/testnndata")

AttributeError: Can't pickle local object 'CoordxifyOperation.get_scalers.<locals>.<lambda>'

In [24]:
NNP.__dict__

{'interpolator': <scipy.interpolate._rbfinterp.RBFInterpolator at 0x7fb33651cc10>,
 'sky': array([0.15077469, 0.1495934 , 0.14423648, 0.14433482, 0.14747137,
        0.14836056, 0.14531086, 0.14922931, 0.14873182, 0.14719386,
        0.14742225, 0.14853853, 0.14872931, 0.14798906, 0.14843427,
        0.14942387, 0.15094892, 0.15054792, 0.15677576, 0.19068839,
        0.17415853, 0.15311395, 0.15320229, 0.16651898, 0.17029691,
        0.15508382, 0.18025812, 0.1883331 , 0.16233235, 0.16886398,
        0.16669567, 0.15809255, 0.31407816, 0.52847163, 0.16061403,
        0.16233161, 0.16050382, 0.16841212, 0.16914596, 0.16412062,
        0.1623135 , 0.16355638, 0.17055147, 0.17649125, 0.16981551,
        0.16835615, 0.16894306, 0.16776282, 0.1689735 , 0.17108565,
        0.21743374, 0.21017425, 0.18578376, 0.17103679, 0.17821553,
        0.18634029, 0.19609469, 0.25088166, 0.22023136, 0.19109764,
        0.18437969, 0.18709035, 0.17928734, 0.24631951, 0.32752443,
        0.17920501, 0.1754

In [20]:
PP.Object

# Testing

In [13]:
label = NNP.uniform_label_sampler(10)

In [14]:
data = NNP.gen_data_from_label(label)

In [15]:
label

array([[0.57925788, 0.39948807, 0.64215741, 0.02337675, 0.73335041],
       [0.26888795, 0.54853334, 0.88590765, 0.13200856, 0.66044418],
       [0.88733086, 0.30163277, 0.00984617, 0.41457628, 0.38629944],
       [0.04600896, 0.49115956, 0.51215172, 0.89300685, 0.56592791],
       [0.96803737, 0.92696633, 0.97286327, 0.26634597, 0.46174536],
       [0.50839872, 0.01970731, 0.00142196, 0.08923567, 0.99983921],
       [0.79577932, 0.70621893, 0.46475822, 0.82658641, 0.11810102],
       [0.86640731, 0.71509963, 0.60395408, 0.04339222, 0.79145322],
       [0.47641478, 0.13259609, 0.76819618, 0.74681398, 0.33790292],
       [0.76201683, 0.61663583, 0.47329428, 0.41569987, 0.70014011]])

In [16]:
data

array([[14.64356868, 14.63281605, 14.63414598, ..., 14.22274357,
        14.23333884, 14.22040087],
       [14.72139445, 14.7157282 , 14.71506144, ..., 14.29114978,
        14.2990678 , 14.28839015],
       [14.60988994, 14.58849995, 14.58328216, ..., 14.19887966,
        14.2052876 , 14.18988353],
       ...,
       [14.89700907, 14.8831864 , 14.88138988, ..., 14.44433574,
        14.44996594, 14.43302246],
       [14.42499533, 14.41179017, 14.41130061, ..., 14.03425995,
        14.04635907, 14.03335774],
       [14.81636442, 14.8020901 , 14.79566017, ..., 14.37646682,
        14.38028096, 14.36439799]])

In [17]:
sigma = NNP.Obs.get_log_sigma(data, log=1)

In [18]:
sigma

array([[0.00020975, 0.00021089, 0.00021075, ..., 0.00025934, 0.00025796,
        0.00025965],
       [0.00020169, 0.00020227, 0.00020234, ..., 0.00025053, 0.00024953,
        0.00025088],
       [0.00021334, 0.00021565, 0.00021622, ..., 0.00026249, 0.00026164,
        0.00026368],
       ...,
       [0.00018464, 0.00018593, 0.0001861 , ..., 0.0002319 , 0.00023124,
        0.00023323],
       [0.00023417, 0.00023574, 0.00023579, ..., 0.00028528, 0.00028354,
        0.00028541],
       [0.00019228, 0.00019367, 0.0001943 , ..., 0.00023997, 0.00023951,
        0.00024144]])