In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
PROJECT_PATH = '/home/swei20/PIML_v1/'
import sys
sys.path.insert(0, PROJECT_PATH)

In [3]:
import os
import numpy as np
import matplotlib.pyplot as plt


In [9]:
from PIML.gateway.loaderIF.nnpreploaderIF import StellarNNPrepLoaderIF

In [10]:
loader = StellarNNPrepLoaderIF()

In [11]:
DATA_DIR = "/home/swei20/PIML_v1/test/testdata/testnnprepdata"

In [12]:
loader.set_path(DATA_DIR)

In [13]:
NNP = loader.load()

In [8]:
PARAMS = {
    "data": {"rng" : np.array([4., 5., 3., 5., 3.])},
    "op": {"step": 10},
    "model": {},
}

In [5]:
from PIML.gateway.processIF.nnprepprocessIF.nnprepprocessIF import StellarNNPrepProcessIF

In [6]:
PP = StellarNNPrepProcessIF()

In [15]:
PP.interact_on_NNPrep(PARAMS, NNP)

# Testing

In [19]:
label = NNP.uniform_label_sampler(10)

In [20]:
data = NNP.gen_data_from_label(label)

In [21]:
label

array([[0.02896091, 0.83019123, 0.20082358, 0.61621908, 0.030695  ],
       [0.08119587, 0.49066949, 0.60476662, 0.9052464 , 0.47738789],
       [0.14785856, 0.24177932, 0.81184985, 0.24650513, 0.70769062],
       [0.21688785, 0.08479568, 0.99533725, 0.38757631, 0.04836971],
       [0.84848274, 0.80089634, 0.5458746 , 0.79435848, 0.11339214],
       [0.50621502, 0.36649768, 0.50200319, 0.06489525, 0.39646959],
       [0.76989351, 0.91201292, 0.93862854, 0.22817585, 0.63573508],
       [0.08078345, 0.37446156, 0.28385928, 0.83501212, 0.44581244],
       [0.12918521, 0.5019101 , 0.73024796, 0.34317398, 0.38853876],
       [0.57332789, 0.35406037, 0.38534368, 0.2658752 , 0.35650611]])

In [22]:
data

array([[14.91299832, 14.90809977, 14.90114621, ..., 14.47891044,
        14.47862382, 14.46562758],
       [14.67213596, 14.6656246 , 14.65908726, ..., 14.25322491,
        14.25735447, 14.24708688],
       [14.4854901 , 14.47930401, 14.47985998, ..., 14.08910565,
        14.09992834, 14.09031406],
       ...,
       [14.59597307, 14.58917144, 14.5832121 , ..., 14.19021487,
        14.19558749, 14.18538634],
       [14.67729194, 14.67237998, 14.67076672, ..., 14.2558369 ,
        14.26308688, 14.25325533],
       [14.61298654, 14.60168022, 14.60074231, ..., 14.199294  ,
        14.20885356, 14.19558852]])

In [31]:
sigma = NNP.Obs.get_log_sigma(data, log=1)

In [32]:
sigma

array([[0.00018316, 0.00018362, 0.00018426, ..., 0.00022789, 0.00022792,
        0.00022942],
       [0.00020676, 0.00020743, 0.00020812, ..., 0.00025538, 0.00025485,
        0.00025617],
       [0.00022714, 0.00022785, 0.00022778, ..., 0.00027747, 0.00027596,
        0.0002773 ],
       ...,
       [0.00021484, 0.00021558, 0.00021622, ..., 0.00026364, 0.00026292,
        0.00026428],
       [0.00020622, 0.00020673, 0.0002069 , ..., 0.00025504, 0.00025411,
        0.00025537],
       [0.00021301, 0.00021422, 0.00021432, ..., 0.00026243, 0.00026117,
        0.00026292]])