In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
PROJECT_PATH = '/home/swei20/PIML_v1/'
import sys
sys.path.insert(0, PROJECT_PATH)

In [3]:
import os
import numpy as np

In [4]:
from PIML.gateway.loaderIF.baseloaderIF import SpecGridLoaderIF


In [5]:
GRID_PATH="/datascope/subaru/user/swei20/data/pfsspec/import/stellar/grid"
FILE_PATH=os.path.join(GRID_PATH, "bosz_5000_RHB.h5")

In [6]:
PARAMS = {
    "data": {"DATA_PATH": FILE_PATH},
    "op"  : { 
        "arm" : "RedM",
        "step": 10
    }
}

In [7]:
MODEL_TYPES = {"Resolution": "Alex"}

In [8]:
SGL = SpecGridLoaderIF()
SGL.set_data_path(FILE_PATH)
SpecGrid = SGL.load()

In [9]:
from PIML.crust.operation.boxoperation import StellarBoxOperation

In [10]:
OP = StellarBoxOperation("R")

In [13]:
OP.perform_on_Box(SpecGrid)

In [14]:
OP.box

{'name': 'R',
 'min': array([-1.0e+00,  5.5e+03,  2.0e+00, -7.5e-01, -2.5e-01]),
 'max': array([0.00e+00, 6.75e+03, 3.50e+00, 5.00e-01, 5.00e-01]),
 'rng': array([1.00e+00, 1.25e+03, 1.50e+00, 1.25e+00, 7.50e-01]),
 'num': array([4., 5., 3., 5., 3.]),
 'mid': array([-5.0e-01,  6.0e+03,  2.5e+00, -2.5e-01,  0.0e+00])}

In [18]:
SpecGrid.coord.min(axis=0)

array([-1.0e+00,  5.5e+03,  2.0e+00, -7.5e-01, -2.5e-01])

In [23]:
assert(SpecGrid.dfcoord.min().values <=OP.PhyMin)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
SpecG

In [20]:
idx = SpecGrid.coord_idx

In [ ]:
idx

In [21]:

(idx[0] == 0).all()

False

In [22]:
SpecGrid

In [23]:
isinstance("box", SpecGrid)

TypeError: isinstance() arg 2 must be a type or tuple of types

In [76]:
xgrid = np.mgrid[0:5,0:5]

In [77]:
xgrid.shape

(2, 5, 5)

In [36]:
xgrid

array([0, 1, 2, 3, 4])

In [30]:

x = xgrid[0]
y = xgrid[1]

In [33]:
np.meshgrid(10)

[array([10])]

In [37]:
x.flatten()

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [38]:
y.flatten()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4])

In [64]:
xflat = xgrid.reshape(2, -1).T

In [104]:
yflats=np.tile(yflat, (2,1)).T

In [99]:
xgrid

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [65]:
yflat = xgrid[0].flatten()

In [98]:
yflat

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [66]:
xflat

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4]])

In [67]:
from scipy.interpolate import RBFInterpolator

In [68]:
interpolator = RBFInterpolator(xflat, yflat, kernel="gaussian", epsilon=0.5)


In [78]:
test = np.array([[2,2]])

In [88]:
test = np.array([[1.5,1.5],[2,2]])

In [109]:
a = interpolator(test)

In [110]:
a

array([1.53468762, 2.        ])

In [112]:
interpolator2d = RBFInterpolator(xflat, yflats, kernel="gaussian", epsilon=0.5)
aa = interpolator2d(test)

In [113]:
aa.round(1)

array([[1.5, 1.5],
       [2. , 2. ]])

In [95]:
SpecGrid.a = 1

In [97]:
hasattr(SpecGrid, 'b')

False